FROM ruby:2.4.1-alpine

RUN echo "@edge https://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
 && apk -U upgrade \
 && apk add -t build-dependencies \
    build-base \
    libxml2-dev \
    libxslt-dev \
    postgresql-dev \
    protobuf-dev \
    python \
 && apk add \
    ca-certificates \
    ffmpeg \
    file \
    git \
    imagemagick@edge \
    libpq \
    libxml2 \
    libxslt \
    nodejs-npm@edge \
    nodejs@edge \
    protobuf \
    su-exec \
    tini \
 && npm install -g npm@3 && npm install -g yarn \
 && update-ca-certificates \
 && rm -rf /tmp/* /var/cache/apk/*

ENV UID=991 GID=991 \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_ENV=development \ NODE_ENV=development

EXPOSE 3000 4000

WORKDIR /mastodon

RUN yarn config set ignore-optional true \
 && yarn config set cache-folder /usr/local/yarn \
 && bundle config without production

#COPY Gemfile Gemfile.lock package.json yarn.lock /mastodon/

#RUN bundle install --without production \
# && yarn --ignore-optional --pure-lockfile

# COPY docker_entrypoint.sh /usr/local/bin/run
# RUN chmod +x /usr/local/bin/run
# ENTRYPOINT ["/usr/local/bin/run"]

COPY . /mastodon
